language: java

matrix:
    include:
        - os: linux
          jdk: openjdk8
        - os: osx
          osx_image: xcode8.3

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update        ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gradle; fi

script:
    - gradle build -i

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gradle jacocoTestReport coveralls; fi
